# Generated by Django 6.0.5 on 2026-05-23 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='attendance_status',
            field=models.CharField(choices=[('UNKNOWN', 'Unknown'), ('SHOWED', 'showed up'), ('NO_SHOW', 'no-showed')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gymhall'),
        ),
    ]
