# Generated by Django 6.0.5 on 2026-05-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_schedule_attendance_status_user_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
